theme = "sevastopol"

[editor]
true-color = true
bufferline = "always"
color-modes = true
popup-border = "all"
cursorline = true
rulers = [82]

# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"

[editor.statusline]
left = [
        "mode",
        "spinner",
        "file-type",
        "file-name",
        "read-only-indicator",
        "file-modification-indicator",
        "version-control"
        ]

right = [
        "diagnostics",
        "selections",
        "register",
        "position",
        "total-line-numbers",
        "file-encoding",
        "file-line-ending"
        ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true
